// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: beatmap_difficulty.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TournamentAssistantShared.Models {

  /// <summary>Holder for reflection information generated from beatmap_difficulty.proto</summary>
  public static partial class BeatmapDifficultyReflection {

    #region Descriptor
    /// <summary>File descriptor for beatmap_difficulty.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BeatmapDifficultyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhiZWF0bWFwX2RpZmZpY3VsdHkucHJvdG8SIFRvdXJuYW1lbnRBc3Npc3Rh",
            "bnRTaGFyZWQuTW9kZWxzKk8KEUJlYXRtYXBEaWZmaWN1bHR5EggKBEVhc3kQ",
            "ABIKCgZOb3JtYWwQARIICgRIYXJkEAISCgoGRXhwZXJ0EAMSDgoKRXhwZXJ0",
            "UGx1cxAEQiOqAiBUb3VybmFtZW50QXNzaXN0YW50U2hhcmVkLk1vZGVsc2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::TournamentAssistantShared.Models.BeatmapDifficulty), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum BeatmapDifficulty {
    [pbr::OriginalName("Easy")] Easy = 0,
    [pbr::OriginalName("Normal")] Normal = 1,
    [pbr::OriginalName("Hard")] Hard = 2,
    [pbr::OriginalName("Expert")] Expert = 3,
    [pbr::OriginalName("ExpertPlus")] ExpertPlus = 4,
  }

  #endregion

}

#endregion Designer generated code
