// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "commands.proto" (package "proto.packets", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Channel } from './discord.js';
import { GameplayParameters } from './models.js';
/**
 * ---- Commands (DO something!) ---- //
 *
 * @generated from protobuf message proto.packets.Command
 */
export interface Command {
    /**
     * @generated from protobuf oneof: type
     */
    type: {
        oneofKind: "heartbeat";
        /**
         * @generated from protobuf field: bool heartbeat = 1;
         */
        heartbeat: boolean; // Is this really a command?
    } | {
        oneofKind: "returnToMenu";
        /**
         * @generated from protobuf field: bool return_to_menu = 2;
         */
        returnToMenu: boolean;
    } | {
        oneofKind: "delayTestFinish";
        /**
         * @generated from protobuf field: bool delay_test_finish = 3;
         */
        delayTestFinish: boolean;
    } | {
        oneofKind: "streamSyncShowImage";
        /**
         * @generated from protobuf field: bool stream_sync_show_image = 4;
         */
        streamSyncShowImage: boolean;
    } | {
        oneofKind: "playSong";
        /**
         * @generated from protobuf field: proto.packets.Command.PlaySong play_song = 6;
         */
        playSong: Command_PlaySong;
    } | {
        oneofKind: "sendBotMessage";
        /**
         * @generated from protobuf field: proto.packets.Command.SendBotMessage send_bot_message = 7;
         */
        sendBotMessage: Command_SendBotMessage;
    } | {
        oneofKind: "discordAuthorize";
        /**
         * @generated from protobuf field: string discord_authorize = 9;
         */
        discordAuthorize: string;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message proto.packets.Command.PlaySong
 */
export interface Command_PlaySong {
    /**
     * @generated from protobuf field: proto.models.GameplayParameters gameplay_parameters = 1;
     */
    gameplayParameters?: GameplayParameters;
}
/**
 * @generated from protobuf message proto.packets.Command.SendBotMessage
 */
export interface Command_SendBotMessage {
    /**
     * @generated from protobuf field: proto.discord.Channel channel = 1;
     */
    channel?: Channel;
    /**
     * @generated from protobuf field: string message = 2;
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Command$Type extends MessageType<Command> {
    constructor() {
        super("proto.packets.Command", [
            { no: 1, name: "heartbeat", kind: "scalar", oneof: "type", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "return_to_menu", kind: "scalar", oneof: "type", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "delay_test_finish", kind: "scalar", oneof: "type", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "stream_sync_show_image", kind: "scalar", oneof: "type", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "play_song", kind: "message", oneof: "type", T: () => Command_PlaySong },
            { no: 7, name: "send_bot_message", kind: "message", oneof: "type", T: () => Command_SendBotMessage },
            { no: 9, name: "discord_authorize", kind: "scalar", oneof: "type", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Command>): Command {
        const message = { type: { oneofKind: undefined } };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Command>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Command): Command {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool heartbeat */ 1:
                    message.type = {
                        oneofKind: "heartbeat",
                        heartbeat: reader.bool()
                    };
                    break;
                case /* bool return_to_menu */ 2:
                    message.type = {
                        oneofKind: "returnToMenu",
                        returnToMenu: reader.bool()
                    };
                    break;
                case /* bool delay_test_finish */ 3:
                    message.type = {
                        oneofKind: "delayTestFinish",
                        delayTestFinish: reader.bool()
                    };
                    break;
                case /* bool stream_sync_show_image */ 4:
                    message.type = {
                        oneofKind: "streamSyncShowImage",
                        streamSyncShowImage: reader.bool()
                    };
                    break;
                case /* proto.packets.Command.PlaySong play_song */ 6:
                    message.type = {
                        oneofKind: "playSong",
                        playSong: Command_PlaySong.internalBinaryRead(reader, reader.uint32(), options, (message.type as any).playSong)
                    };
                    break;
                case /* proto.packets.Command.SendBotMessage send_bot_message */ 7:
                    message.type = {
                        oneofKind: "sendBotMessage",
                        sendBotMessage: Command_SendBotMessage.internalBinaryRead(reader, reader.uint32(), options, (message.type as any).sendBotMessage)
                    };
                    break;
                case /* string discord_authorize */ 9:
                    message.type = {
                        oneofKind: "discordAuthorize",
                        discordAuthorize: reader.string()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Command, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool heartbeat = 1; */
        if (message.type.oneofKind === "heartbeat")
            writer.tag(1, WireType.Varint).bool(message.type.heartbeat);
        /* bool return_to_menu = 2; */
        if (message.type.oneofKind === "returnToMenu")
            writer.tag(2, WireType.Varint).bool(message.type.returnToMenu);
        /* bool delay_test_finish = 3; */
        if (message.type.oneofKind === "delayTestFinish")
            writer.tag(3, WireType.Varint).bool(message.type.delayTestFinish);
        /* bool stream_sync_show_image = 4; */
        if (message.type.oneofKind === "streamSyncShowImage")
            writer.tag(4, WireType.Varint).bool(message.type.streamSyncShowImage);
        /* proto.packets.Command.PlaySong play_song = 6; */
        if (message.type.oneofKind === "playSong")
            Command_PlaySong.internalBinaryWrite(message.type.playSong, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* proto.packets.Command.SendBotMessage send_bot_message = 7; */
        if (message.type.oneofKind === "sendBotMessage")
            Command_SendBotMessage.internalBinaryWrite(message.type.sendBotMessage, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* string discord_authorize = 9; */
        if (message.type.oneofKind === "discordAuthorize")
            writer.tag(9, WireType.LengthDelimited).string(message.type.discordAuthorize);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.packets.Command
 */
export const Command = new Command$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Command_PlaySong$Type extends MessageType<Command_PlaySong> {
    constructor() {
        super("proto.packets.Command.PlaySong", [
            { no: 1, name: "gameplay_parameters", kind: "message", T: () => GameplayParameters }
        ]);
    }
    create(value?: PartialMessage<Command_PlaySong>): Command_PlaySong {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Command_PlaySong>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Command_PlaySong): Command_PlaySong {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.models.GameplayParameters gameplay_parameters */ 1:
                    message.gameplayParameters = GameplayParameters.internalBinaryRead(reader, reader.uint32(), options, message.gameplayParameters);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Command_PlaySong, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.models.GameplayParameters gameplay_parameters = 1; */
        if (message.gameplayParameters)
            GameplayParameters.internalBinaryWrite(message.gameplayParameters, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.packets.Command.PlaySong
 */
export const Command_PlaySong = new Command_PlaySong$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Command_SendBotMessage$Type extends MessageType<Command_SendBotMessage> {
    constructor() {
        super("proto.packets.Command.SendBotMessage", [
            { no: 1, name: "channel", kind: "message", T: () => Channel },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Command_SendBotMessage>): Command_SendBotMessage {
        const message = { message: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Command_SendBotMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Command_SendBotMessage): Command_SendBotMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proto.discord.Channel channel */ 1:
                    message.channel = Channel.internalBinaryRead(reader, reader.uint32(), options, message.channel);
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Command_SendBotMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proto.discord.Channel channel = 1; */
        if (message.channel)
            Channel.internalBinaryWrite(message.channel, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto.packets.Command.SendBotMessage
 */
export const Command_SendBotMessage = new Command_SendBotMessage$Type();
