// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf/Models/Packets/connect_response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TournamentAssistantShared.Models.Packets {

  /// <summary>Holder for reflection information generated from protobuf/Models/Packets/connect_response.proto</summary>
  public static partial class ConnectResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for protobuf/Models/Packets/connect_response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConnectResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5wcm90b2J1Zi9Nb2RlbHMvUGFja2V0cy9jb25uZWN0X3Jlc3BvbnNlLnBy",
            "b3RvEihUb3VybmFtZW50QXNzaXN0YW50U2hhcmVkLk1vZGVscy5QYWNrZXRz",
            "GiZwcm90b2J1Zi9Nb2RlbHMvUGFja2V0cy9yZXNwb25zZS5wcm90bxohcHJv",
            "dG9idWYvTW9kZWxzL2Nvb3JkaW5hdG9yLnByb3RvGhxwcm90b2J1Zi9Nb2Rl",
            "bHMvcGxheWVyLnByb3RvGhtwcm90b2J1Zi9Nb2RlbHMvc3RhdGUucHJvdG8i",
            "sQIKD0Nvbm5lY3RSZXNwb25zZRJECghyZXNwb25zZRgBIAEoCzIyLlRvdXJu",
            "YW1lbnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxzLlBhY2tldHMuUmVzcG9uc2US",
            "RAoLY29vcmRpbmF0b3IYAiABKAsyLS5Ub3VybmFtZW50QXNzaXN0YW50U2hh",
            "cmVkLk1vZGVscy5Db29yZGluYXRvckgAEjoKBnBsYXllchgDIAEoCzIoLlRv",
            "dXJuYW1lbnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxzLlBsYXllckgAEjYKBXN0",
            "YXRlGAQgASgLMicuVG91cm5hbWVudEFzc2lzdGFudFNoYXJlZC5Nb2RlbHMu",
            "U3RhdGUSFgoOc2VydmVyX3ZlcnNpb24YBSABKAVCBgoEdXNlckIrqgIoVG91",
            "cm5hbWVudEFzc2lzdGFudFNoYXJlZC5Nb2RlbHMuUGFja2V0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TournamentAssistantShared.Models.Packets.ResponseReflection.Descriptor, global::TournamentAssistantShared.Models.CoordinatorReflection.Descriptor, global::TournamentAssistantShared.Models.PlayerReflection.Descriptor, global::TournamentAssistantShared.Models.StateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TournamentAssistantShared.Models.Packets.ConnectResponse), global::TournamentAssistantShared.Models.Packets.ConnectResponse.Parser, new[]{ "Response", "Coordinator", "Player", "State", "ServerVersion" }, new[]{ "User" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConnectResponse : pb::IMessage<ConnectResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConnectResponse> _parser = new pb::MessageParser<ConnectResponse>(() => new ConnectResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConnectResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TournamentAssistantShared.Models.Packets.ConnectResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectResponse(ConnectResponse other) : this() {
      response_ = other.response_ != null ? other.response_.Clone() : null;
      state_ = other.state_ != null ? other.state_.Clone() : null;
      serverVersion_ = other.serverVersion_;
      switch (other.UserCase) {
        case UserOneofCase.Coordinator:
          Coordinator = other.Coordinator.Clone();
          break;
        case UserOneofCase.Player:
          Player = other.Player.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectResponse Clone() {
      return new ConnectResponse(this);
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 1;
    private global::TournamentAssistantShared.Models.Packets.Response response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TournamentAssistantShared.Models.Packets.Response Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    /// <summary>Field number for the "coordinator" field.</summary>
    public const int CoordinatorFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TournamentAssistantShared.Models.Coordinator Coordinator {
      get { return userCase_ == UserOneofCase.Coordinator ? (global::TournamentAssistantShared.Models.Coordinator) user_ : null; }
      set {
        user_ = value;
        userCase_ = value == null ? UserOneofCase.None : UserOneofCase.Coordinator;
      }
    }

    /// <summary>Field number for the "player" field.</summary>
    public const int PlayerFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TournamentAssistantShared.Models.Player Player {
      get { return userCase_ == UserOneofCase.Player ? (global::TournamentAssistantShared.Models.Player) user_ : null; }
      set {
        user_ = value;
        userCase_ = value == null ? UserOneofCase.None : UserOneofCase.Player;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 4;
    private global::TournamentAssistantShared.Models.State state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TournamentAssistantShared.Models.State State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "server_version" field.</summary>
    public const int ServerVersionFieldNumber = 5;
    private int serverVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ServerVersion {
      get { return serverVersion_; }
      set {
        serverVersion_ = value;
      }
    }

    private object user_;
    /// <summary>Enum of possible cases for the "user" oneof.</summary>
    public enum UserOneofCase {
      None = 0,
      Coordinator = 2,
      Player = 3,
    }
    private UserOneofCase userCase_ = UserOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserOneofCase UserCase {
      get { return userCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUser() {
      userCase_ = UserOneofCase.None;
      user_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConnectResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConnectResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Response, other.Response)) return false;
      if (!object.Equals(Coordinator, other.Coordinator)) return false;
      if (!object.Equals(Player, other.Player)) return false;
      if (!object.Equals(State, other.State)) return false;
      if (ServerVersion != other.ServerVersion) return false;
      if (UserCase != other.UserCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (response_ != null) hash ^= Response.GetHashCode();
      if (userCase_ == UserOneofCase.Coordinator) hash ^= Coordinator.GetHashCode();
      if (userCase_ == UserOneofCase.Player) hash ^= Player.GetHashCode();
      if (state_ != null) hash ^= State.GetHashCode();
      if (ServerVersion != 0) hash ^= ServerVersion.GetHashCode();
      hash ^= (int) userCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (response_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Response);
      }
      if (userCase_ == UserOneofCase.Coordinator) {
        output.WriteRawTag(18);
        output.WriteMessage(Coordinator);
      }
      if (userCase_ == UserOneofCase.Player) {
        output.WriteRawTag(26);
        output.WriteMessage(Player);
      }
      if (state_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(State);
      }
      if (ServerVersion != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ServerVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (response_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Response);
      }
      if (userCase_ == UserOneofCase.Coordinator) {
        output.WriteRawTag(18);
        output.WriteMessage(Coordinator);
      }
      if (userCase_ == UserOneofCase.Player) {
        output.WriteRawTag(26);
        output.WriteMessage(Player);
      }
      if (state_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(State);
      }
      if (ServerVersion != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ServerVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (userCase_ == UserOneofCase.Coordinator) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Coordinator);
      }
      if (userCase_ == UserOneofCase.Player) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Player);
      }
      if (state_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(State);
      }
      if (ServerVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConnectResponse other) {
      if (other == null) {
        return;
      }
      if (other.response_ != null) {
        if (response_ == null) {
          Response = new global::TournamentAssistantShared.Models.Packets.Response();
        }
        Response.MergeFrom(other.Response);
      }
      if (other.state_ != null) {
        if (state_ == null) {
          State = new global::TournamentAssistantShared.Models.State();
        }
        State.MergeFrom(other.State);
      }
      if (other.ServerVersion != 0) {
        ServerVersion = other.ServerVersion;
      }
      switch (other.UserCase) {
        case UserOneofCase.Coordinator:
          if (Coordinator == null) {
            Coordinator = new global::TournamentAssistantShared.Models.Coordinator();
          }
          Coordinator.MergeFrom(other.Coordinator);
          break;
        case UserOneofCase.Player:
          if (Player == null) {
            Player = new global::TournamentAssistantShared.Models.Player();
          }
          Player.MergeFrom(other.Player);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (response_ == null) {
              Response = new global::TournamentAssistantShared.Models.Packets.Response();
            }
            input.ReadMessage(Response);
            break;
          }
          case 18: {
            global::TournamentAssistantShared.Models.Coordinator subBuilder = new global::TournamentAssistantShared.Models.Coordinator();
            if (userCase_ == UserOneofCase.Coordinator) {
              subBuilder.MergeFrom(Coordinator);
            }
            input.ReadMessage(subBuilder);
            Coordinator = subBuilder;
            break;
          }
          case 26: {
            global::TournamentAssistantShared.Models.Player subBuilder = new global::TournamentAssistantShared.Models.Player();
            if (userCase_ == UserOneofCase.Player) {
              subBuilder.MergeFrom(Player);
            }
            input.ReadMessage(subBuilder);
            Player = subBuilder;
            break;
          }
          case 34: {
            if (state_ == null) {
              State = new global::TournamentAssistantShared.Models.State();
            }
            input.ReadMessage(State);
            break;
          }
          case 40: {
            ServerVersion = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (response_ == null) {
              Response = new global::TournamentAssistantShared.Models.Packets.Response();
            }
            input.ReadMessage(Response);
            break;
          }
          case 18: {
            global::TournamentAssistantShared.Models.Coordinator subBuilder = new global::TournamentAssistantShared.Models.Coordinator();
            if (userCase_ == UserOneofCase.Coordinator) {
              subBuilder.MergeFrom(Coordinator);
            }
            input.ReadMessage(subBuilder);
            Coordinator = subBuilder;
            break;
          }
          case 26: {
            global::TournamentAssistantShared.Models.Player subBuilder = new global::TournamentAssistantShared.Models.Player();
            if (userCase_ == UserOneofCase.Player) {
              subBuilder.MergeFrom(Player);
            }
            input.ReadMessage(subBuilder);
            Player = subBuilder;
            break;
          }
          case 34: {
            if (state_ == null) {
              State = new global::TournamentAssistantShared.Models.State();
            }
            input.ReadMessage(State);
            break;
          }
          case 40: {
            ServerVersion = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
