// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TournamentAssistantServer.Database.Contexts;

namespace TournamentAssistantServer.Migrations.WebhookDatabase
{
    [DbContext(typeof(WebhookDatabaseContext))]
    partial class WebhookDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "3.1.29");

            modelBuilder.Entity("TournamentAssistantServer.Database.Models.Webhook", b =>
            {
                b.Property<ulong>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("ID")
                    .HasColumnType("INTEGER");
                b.Property<string>("Guid").HasColumnName("Guid").HasColumnType("TEXT");
                b.Property<bool>("Old").HasColumnName("Old").HasColumnType("INTEGER");
                b.Property<string>("SigningSecret").HasColumnName("SigningSecret").HasColumnType("TEXT");
                b.Property<string>("TournamentId").HasColumnName("TournamentId").HasColumnType("TEXT");
                b.Property<long>("Triggers").HasColumnName("Triggers").HasColumnType("INTEGER");
                b.Property<string>("Url").HasColumnName("Url").HasColumnType("TEXT");
                b.HasKey("ID");
                b.HasIndex("Guid").IsUnique();
                b.HasIndex("TournamentId");
                b.ToTable("Webhooks");
            });
#pragma warning restore 612, 618
        }
    }
}
