// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: connect_response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TournamentAssistantShared.Models.Packets {

  /// <summary>Holder for reflection information generated from connect_response.proto</summary>
  public static partial class ConnectResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for connect_response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConnectResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZjb25uZWN0X3Jlc3BvbnNlLnByb3RvEihUb3VybmFtZW50QXNzaXN0YW50",
            "U2hhcmVkLk1vZGVscy5QYWNrZXRzGg5yZXNwb25zZS5wcm90bxoKdXNlci5w",
            "cm90bxoLc3RhdGUucHJvdG8i3QEKD0Nvbm5lY3RSZXNwb25zZRJECghyZXNw",
            "b25zZRgBIAEoCzIyLlRvdXJuYW1lbnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxz",
            "LlBhY2tldHMuUmVzcG9uc2USNAoEc2VsZhgCIAEoCzImLlRvdXJuYW1lbnRB",
            "c3Npc3RhbnRTaGFyZWQuTW9kZWxzLlVzZXISNgoFc3RhdGUYAyABKAsyJy5U",
            "b3VybmFtZW50QXNzaXN0YW50U2hhcmVkLk1vZGVscy5TdGF0ZRIWCg5zZXJ2",
            "ZXJfdmVyc2lvbhgEIAEoBUIrqgIoVG91cm5hbWVudEFzc2lzdGFudFNoYXJl",
            "ZC5Nb2RlbHMuUGFja2V0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TournamentAssistantShared.Models.Packets.ResponseReflection.Descriptor, global::TournamentAssistantShared.Models.UserReflection.Descriptor, global::TournamentAssistantShared.Models.StateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TournamentAssistantShared.Models.Packets.ConnectResponse), global::TournamentAssistantShared.Models.Packets.ConnectResponse.Parser, new[]{ "Response", "Self", "State", "ServerVersion" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConnectResponse : pb::IMessage<ConnectResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConnectResponse> _parser = new pb::MessageParser<ConnectResponse>(() => new ConnectResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConnectResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TournamentAssistantShared.Models.Packets.ConnectResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConnectResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConnectResponse(ConnectResponse other) : this() {
      response_ = other.response_ != null ? other.response_.Clone() : null;
      self_ = other.self_ != null ? other.self_.Clone() : null;
      state_ = other.state_ != null ? other.state_.Clone() : null;
      serverVersion_ = other.serverVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConnectResponse Clone() {
      return new ConnectResponse(this);
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 1;
    private global::TournamentAssistantShared.Models.Packets.Response response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.Packets.Response Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    /// <summary>Field number for the "self" field.</summary>
    public const int SelfFieldNumber = 2;
    private global::TournamentAssistantShared.Models.User self_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.User Self {
      get { return self_; }
      set {
        self_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 3;
    private global::TournamentAssistantShared.Models.State state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.State State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "server_version" field.</summary>
    public const int ServerVersionFieldNumber = 4;
    private int serverVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ServerVersion {
      get { return serverVersion_; }
      set {
        serverVersion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConnectResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConnectResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Response, other.Response)) return false;
      if (!object.Equals(Self, other.Self)) return false;
      if (!object.Equals(State, other.State)) return false;
      if (ServerVersion != other.ServerVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (response_ != null) hash ^= Response.GetHashCode();
      if (self_ != null) hash ^= Self.GetHashCode();
      if (state_ != null) hash ^= State.GetHashCode();
      if (ServerVersion != 0) hash ^= ServerVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (response_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Response);
      }
      if (self_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Self);
      }
      if (state_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(State);
      }
      if (ServerVersion != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ServerVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (response_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Response);
      }
      if (self_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Self);
      }
      if (state_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(State);
      }
      if (ServerVersion != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ServerVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (self_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Self);
      }
      if (state_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(State);
      }
      if (ServerVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConnectResponse other) {
      if (other == null) {
        return;
      }
      if (other.response_ != null) {
        if (response_ == null) {
          Response = new global::TournamentAssistantShared.Models.Packets.Response();
        }
        Response.MergeFrom(other.Response);
      }
      if (other.self_ != null) {
        if (self_ == null) {
          Self = new global::TournamentAssistantShared.Models.User();
        }
        Self.MergeFrom(other.Self);
      }
      if (other.state_ != null) {
        if (state_ == null) {
          State = new global::TournamentAssistantShared.Models.State();
        }
        State.MergeFrom(other.State);
      }
      if (other.ServerVersion != 0) {
        ServerVersion = other.ServerVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (response_ == null) {
              Response = new global::TournamentAssistantShared.Models.Packets.Response();
            }
            input.ReadMessage(Response);
            break;
          }
          case 18: {
            if (self_ == null) {
              Self = new global::TournamentAssistantShared.Models.User();
            }
            input.ReadMessage(Self);
            break;
          }
          case 26: {
            if (state_ == null) {
              State = new global::TournamentAssistantShared.Models.State();
            }
            input.ReadMessage(State);
            break;
          }
          case 32: {
            ServerVersion = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (response_ == null) {
              Response = new global::TournamentAssistantShared.Models.Packets.Response();
            }
            input.ReadMessage(Response);
            break;
          }
          case 18: {
            if (self_ == null) {
              Self = new global::TournamentAssistantShared.Models.User();
            }
            input.ReadMessage(Self);
            break;
          }
          case 26: {
            if (state_ == null) {
              State = new global::TournamentAssistantShared.Models.State();
            }
            input.ReadMessage(State);
            break;
          }
          case 32: {
            ServerVersion = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
