// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TournamentAssistantShared.Models.Packets {

  /// <summary>Holder for reflection information generated from event.proto</summary>
  public static partial class EventReflection {

    #region Descriptor
    /// <summary>File descriptor for event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtldmVudC5wcm90bxIoVG91cm5hbWVudEFzc2lzdGFudFNoYXJlZC5Nb2Rl",
            "bHMuUGFja2V0cxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90byKSAwoFRXZl",
            "bnQSRwoEdHlwZRgBIAEoDjI5LlRvdXJuYW1lbnRBc3Npc3RhbnRTaGFyZWQu",
            "TW9kZWxzLlBhY2tldHMuRXZlbnQuRXZlbnRUeXBlEiwKDmNoYW5nZWRfb2Jq",
            "ZWN0GAIgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueSKRAgoJRXZlbnRUeXBl",
            "Eg8KC1BsYXllckFkZGVkEAASEQoNUGxheWVyVXBkYXRlZBABEg4KClBsYXll",
            "ckxlZnQQAhIUChBDb29yZGluYXRvckFkZGVkEAMSEwoPQ29vcmRpbmF0b3JM",
            "ZWZ0EAQSEAoMTWF0Y2hDcmVhdGVkEAUSEAoMTWF0Y2hVcGRhdGVkEAYSEAoM",
            "TWF0Y2hEZWxldGVkEAcSGQoVUXVhbGlmaWVyRXZlbnRDcmVhdGVkEAgSGQoV",
            "UXVhbGlmaWVyRXZlbnRVcGRhdGVkEAkSGQoVUXVhbGlmaWVyRXZlbnREZWxl",
            "dGVkEAoSDQoJSG9zdEFkZGVkEAsSDwoLSG9zdFJlbW92ZWQQDEIrqgIoVG91",
            "cm5hbWVudEFzc2lzdGFudFNoYXJlZC5Nb2RlbHMuUGFja2V0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TournamentAssistantShared.Models.Packets.Event), global::TournamentAssistantShared.Models.Packets.Event.Parser, new[]{ "Type", "ChangedObject" }, null, new[]{ typeof(global::TournamentAssistantShared.Models.Packets.Event.Types.EventType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Event : pb::IMessage<Event>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Event> _parser = new pb::MessageParser<Event>(() => new Event());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Event> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TournamentAssistantShared.Models.Packets.EventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event(Event other) : this() {
      type_ = other.type_;
      changedObject_ = other.changedObject_ != null ? other.changedObject_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event Clone() {
      return new Event(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::TournamentAssistantShared.Models.Packets.Event.Types.EventType type_ = global::TournamentAssistantShared.Models.Packets.Event.Types.EventType.PlayerAdded;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.Packets.Event.Types.EventType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "changed_object" field.</summary>
    public const int ChangedObjectFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any changedObject_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any ChangedObject {
      get { return changedObject_; }
      set {
        changedObject_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Event);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Event other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(ChangedObject, other.ChangedObject)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::TournamentAssistantShared.Models.Packets.Event.Types.EventType.PlayerAdded) hash ^= Type.GetHashCode();
      if (changedObject_ != null) hash ^= ChangedObject.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::TournamentAssistantShared.Models.Packets.Event.Types.EventType.PlayerAdded) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (changedObject_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedObject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::TournamentAssistantShared.Models.Packets.Event.Types.EventType.PlayerAdded) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (changedObject_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedObject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::TournamentAssistantShared.Models.Packets.Event.Types.EventType.PlayerAdded) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (changedObject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedObject);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Event other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::TournamentAssistantShared.Models.Packets.Event.Types.EventType.PlayerAdded) {
        Type = other.Type;
      }
      if (other.changedObject_ != null) {
        if (changedObject_ == null) {
          ChangedObject = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        ChangedObject.MergeFrom(other.ChangedObject);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::TournamentAssistantShared.Models.Packets.Event.Types.EventType) input.ReadEnum();
            break;
          }
          case 18: {
            if (changedObject_ == null) {
              ChangedObject = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ChangedObject);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::TournamentAssistantShared.Models.Packets.Event.Types.EventType) input.ReadEnum();
            break;
          }
          case 18: {
            if (changedObject_ == null) {
              ChangedObject = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(ChangedObject);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Event message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum EventType {
        [pbr::OriginalName("PlayerAdded")] PlayerAdded = 0,
        [pbr::OriginalName("PlayerUpdated")] PlayerUpdated = 1,
        [pbr::OriginalName("PlayerLeft")] PlayerLeft = 2,
        [pbr::OriginalName("CoordinatorAdded")] CoordinatorAdded = 3,
        [pbr::OriginalName("CoordinatorLeft")] CoordinatorLeft = 4,
        [pbr::OriginalName("MatchCreated")] MatchCreated = 5,
        [pbr::OriginalName("MatchUpdated")] MatchUpdated = 6,
        [pbr::OriginalName("MatchDeleted")] MatchDeleted = 7,
        [pbr::OriginalName("QualifierEventCreated")] QualifierEventCreated = 8,
        [pbr::OriginalName("QualifierEventUpdated")] QualifierEventUpdated = 9,
        [pbr::OriginalName("QualifierEventDeleted")] QualifierEventDeleted = 10,
        [pbr::OriginalName("HostAdded")] HostAdded = 11,
        [pbr::OriginalName("HostRemoved")] HostRemoved = 12,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
