// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: match.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TournamentAssistantShared.Models {

  /// <summary>Holder for reflection information generated from match.proto</summary>
  public static partial class MatchReflection {

    #region Descriptor
    /// <summary>File descriptor for match.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MatchReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgttYXRjaC5wcm90bxIgVG91cm5hbWVudEFzc2lzdGFudFNoYXJlZC5Nb2Rl",
            "bHMaCnVzZXIucHJvdG8aDHBsYXllci5wcm90bxobcHJldmlld19iZWF0bWFw",
            "X2xldmVsLnByb3RvGhRjaGFyYWN0ZXJpc3RpYy5wcm90byLHAgoFTWF0Y2gS",
            "DAoEZ3VpZBgBIAEoCRI5CgdwbGF5ZXJzGAIgAygLMiguVG91cm5hbWVudEFz",
            "c2lzdGFudFNoYXJlZC5Nb2RlbHMuUGxheWVyEjYKBmxlYWRlchgDIAEoCzIm",
            "LlRvdXJuYW1lbnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxzLlVzZXISTQoOc2Vs",
            "ZWN0ZWRfbGV2ZWwYBSABKAsyNS5Ub3VybmFtZW50QXNzaXN0YW50U2hhcmVk",
            "Lk1vZGVscy5QcmV2aWV3QmVhdG1hcExldmVsElEKF3NlbGVjdGVkX2NoYXJh",
            "Y3RlcmlzdGljGAYgASgLMjAuVG91cm5hbWVudEFzc2lzdGFudFNoYXJlZC5N",
            "b2RlbHMuQ2hhcmFjdGVyaXN0aWMSGwoTc2VsZWN0ZWRfZGlmZmljdWx0eRgH",
            "IAEoBUIjqgIgVG91cm5hbWVudEFzc2lzdGFudFNoYXJlZC5Nb2RlbHNiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TournamentAssistantShared.Models.UserReflection.Descriptor, global::TournamentAssistantShared.Models.PlayerReflection.Descriptor, global::TournamentAssistantShared.Models.PreviewBeatmapLevelReflection.Descriptor, global::TournamentAssistantShared.Models.CharacteristicReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TournamentAssistantShared.Models.Match), global::TournamentAssistantShared.Models.Match.Parser, new[]{ "Guid", "Players", "Leader", "SelectedLevel", "SelectedCharacteristic", "SelectedDifficulty" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Match : pb::IMessage<Match>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Match> _parser = new pb::MessageParser<Match>(() => new Match());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Match> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TournamentAssistantShared.Models.MatchReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Match() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Match(Match other) : this() {
      guid_ = other.guid_;
      players_ = other.players_.Clone();
      leader_ = other.leader_ != null ? other.leader_.Clone() : null;
      selectedLevel_ = other.selectedLevel_ != null ? other.selectedLevel_.Clone() : null;
      selectedCharacteristic_ = other.selectedCharacteristic_ != null ? other.selectedCharacteristic_.Clone() : null;
      selectedDifficulty_ = other.selectedDifficulty_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Match Clone() {
      return new Match(this);
    }

    /// <summary>Field number for the "guid" field.</summary>
    public const int GuidFieldNumber = 1;
    private string guid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Guid {
      get { return guid_; }
      set {
        guid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::TournamentAssistantShared.Models.Player> _repeated_players_codec
        = pb::FieldCodec.ForMessage(18, global::TournamentAssistantShared.Models.Player.Parser);
    private readonly pbc::RepeatedField<global::TournamentAssistantShared.Models.Player> players_ = new pbc::RepeatedField<global::TournamentAssistantShared.Models.Player>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TournamentAssistantShared.Models.Player> Players {
      get { return players_; }
    }

    /// <summary>Field number for the "leader" field.</summary>
    public const int LeaderFieldNumber = 3;
    private global::TournamentAssistantShared.Models.User leader_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.User Leader {
      get { return leader_; }
      set {
        leader_ = value;
      }
    }

    /// <summary>Field number for the "selected_level" field.</summary>
    public const int SelectedLevelFieldNumber = 5;
    private global::TournamentAssistantShared.Models.PreviewBeatmapLevel selectedLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.PreviewBeatmapLevel SelectedLevel {
      get { return selectedLevel_; }
      set {
        selectedLevel_ = value;
      }
    }

    /// <summary>Field number for the "selected_characteristic" field.</summary>
    public const int SelectedCharacteristicFieldNumber = 6;
    private global::TournamentAssistantShared.Models.Characteristic selectedCharacteristic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.Characteristic SelectedCharacteristic {
      get { return selectedCharacteristic_; }
      set {
        selectedCharacteristic_ = value;
      }
    }

    /// <summary>Field number for the "selected_difficulty" field.</summary>
    public const int SelectedDifficultyFieldNumber = 7;
    private int selectedDifficulty_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SelectedDifficulty {
      get { return selectedDifficulty_; }
      set {
        selectedDifficulty_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Match);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Match other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Guid != other.Guid) return false;
      if(!players_.Equals(other.players_)) return false;
      if (!object.Equals(Leader, other.Leader)) return false;
      if (!object.Equals(SelectedLevel, other.SelectedLevel)) return false;
      if (!object.Equals(SelectedCharacteristic, other.SelectedCharacteristic)) return false;
      if (SelectedDifficulty != other.SelectedDifficulty) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Guid.Length != 0) hash ^= Guid.GetHashCode();
      hash ^= players_.GetHashCode();
      if (leader_ != null) hash ^= Leader.GetHashCode();
      if (selectedLevel_ != null) hash ^= SelectedLevel.GetHashCode();
      if (selectedCharacteristic_ != null) hash ^= SelectedCharacteristic.GetHashCode();
      if (SelectedDifficulty != 0) hash ^= SelectedDifficulty.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Guid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Guid);
      }
      players_.WriteTo(output, _repeated_players_codec);
      if (leader_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Leader);
      }
      if (selectedLevel_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(SelectedLevel);
      }
      if (selectedCharacteristic_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(SelectedCharacteristic);
      }
      if (SelectedDifficulty != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(SelectedDifficulty);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Guid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Guid);
      }
      players_.WriteTo(ref output, _repeated_players_codec);
      if (leader_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Leader);
      }
      if (selectedLevel_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(SelectedLevel);
      }
      if (selectedCharacteristic_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(SelectedCharacteristic);
      }
      if (SelectedDifficulty != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(SelectedDifficulty);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Guid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Guid);
      }
      size += players_.CalculateSize(_repeated_players_codec);
      if (leader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Leader);
      }
      if (selectedLevel_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SelectedLevel);
      }
      if (selectedCharacteristic_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SelectedCharacteristic);
      }
      if (SelectedDifficulty != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SelectedDifficulty);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Match other) {
      if (other == null) {
        return;
      }
      if (other.Guid.Length != 0) {
        Guid = other.Guid;
      }
      players_.Add(other.players_);
      if (other.leader_ != null) {
        if (leader_ == null) {
          Leader = new global::TournamentAssistantShared.Models.User();
        }
        Leader.MergeFrom(other.Leader);
      }
      if (other.selectedLevel_ != null) {
        if (selectedLevel_ == null) {
          SelectedLevel = new global::TournamentAssistantShared.Models.PreviewBeatmapLevel();
        }
        SelectedLevel.MergeFrom(other.SelectedLevel);
      }
      if (other.selectedCharacteristic_ != null) {
        if (selectedCharacteristic_ == null) {
          SelectedCharacteristic = new global::TournamentAssistantShared.Models.Characteristic();
        }
        SelectedCharacteristic.MergeFrom(other.SelectedCharacteristic);
      }
      if (other.SelectedDifficulty != 0) {
        SelectedDifficulty = other.SelectedDifficulty;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Guid = input.ReadString();
            break;
          }
          case 18: {
            players_.AddEntriesFrom(input, _repeated_players_codec);
            break;
          }
          case 26: {
            if (leader_ == null) {
              Leader = new global::TournamentAssistantShared.Models.User();
            }
            input.ReadMessage(Leader);
            break;
          }
          case 42: {
            if (selectedLevel_ == null) {
              SelectedLevel = new global::TournamentAssistantShared.Models.PreviewBeatmapLevel();
            }
            input.ReadMessage(SelectedLevel);
            break;
          }
          case 50: {
            if (selectedCharacteristic_ == null) {
              SelectedCharacteristic = new global::TournamentAssistantShared.Models.Characteristic();
            }
            input.ReadMessage(SelectedCharacteristic);
            break;
          }
          case 56: {
            SelectedDifficulty = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Guid = input.ReadString();
            break;
          }
          case 18: {
            players_.AddEntriesFrom(ref input, _repeated_players_codec);
            break;
          }
          case 26: {
            if (leader_ == null) {
              Leader = new global::TournamentAssistantShared.Models.User();
            }
            input.ReadMessage(Leader);
            break;
          }
          case 42: {
            if (selectedLevel_ == null) {
              SelectedLevel = new global::TournamentAssistantShared.Models.PreviewBeatmapLevel();
            }
            input.ReadMessage(SelectedLevel);
            break;
          }
          case 50: {
            if (selectedCharacteristic_ == null) {
              SelectedCharacteristic = new global::TournamentAssistantShared.Models.Characteristic();
            }
            input.ReadMessage(SelectedCharacteristic);
            break;
          }
          case 56: {
            SelectedDifficulty = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
