// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: song_finished.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TournamentAssistantShared.Models.Packets {

  /// <summary>Holder for reflection information generated from song_finished.proto</summary>
  public static partial class SongFinishedReflection {

    #region Descriptor
    /// <summary>File descriptor for song_finished.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SongFinishedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNzb25nX2ZpbmlzaGVkLnByb3RvEihUb3VybmFtZW50QXNzaXN0YW50U2hh",
            "cmVkLk1vZGVscy5QYWNrZXRzGgxwbGF5ZXIucHJvdG8aDWJlYXRtYXAucHJv",
            "dG8inAIKDFNvbmdGaW5pc2hlZBI4CgZwbGF5ZXIYASABKAsyKC5Ub3VybmFt",
            "ZW50QXNzaXN0YW50U2hhcmVkLk1vZGVscy5QbGF5ZXISOgoHYmVhdG1hcBgC",
            "IAEoCzIpLlRvdXJuYW1lbnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxzLkJlYXRt",
            "YXASUwoEdHlwZRgDIAEoDjJFLlRvdXJuYW1lbnRBc3Npc3RhbnRTaGFyZWQu",
            "TW9kZWxzLlBhY2tldHMuU29uZ0ZpbmlzaGVkLkNvbXBsZXRpb25UeXBlEg0K",
            "BXNjb3JlGAQgASgFIjIKDkNvbXBsZXRpb25UeXBlEgoKBlBhc3NlZBAAEgoK",
            "BkZhaWxlZBABEggKBFF1aXQQAkIrqgIoVG91cm5hbWVudEFzc2lzdGFudFNo",
            "YXJlZC5Nb2RlbHMuUGFja2V0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TournamentAssistantShared.Models.PlayerReflection.Descriptor, global::TournamentAssistantShared.Models.BeatmapReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TournamentAssistantShared.Models.Packets.SongFinished), global::TournamentAssistantShared.Models.Packets.SongFinished.Parser, new[]{ "Player", "Beatmap", "Type", "Score" }, null, new[]{ typeof(global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SongFinished : pb::IMessage<SongFinished>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SongFinished> _parser = new pb::MessageParser<SongFinished>(() => new SongFinished());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SongFinished> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TournamentAssistantShared.Models.Packets.SongFinishedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SongFinished() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SongFinished(SongFinished other) : this() {
      player_ = other.player_ != null ? other.player_.Clone() : null;
      beatmap_ = other.beatmap_ != null ? other.beatmap_.Clone() : null;
      type_ = other.type_;
      score_ = other.score_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SongFinished Clone() {
      return new SongFinished(this);
    }

    /// <summary>Field number for the "player" field.</summary>
    public const int PlayerFieldNumber = 1;
    private global::TournamentAssistantShared.Models.Player player_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.Player Player {
      get { return player_; }
      set {
        player_ = value;
      }
    }

    /// <summary>Field number for the "beatmap" field.</summary>
    public const int BeatmapFieldNumber = 2;
    private global::TournamentAssistantShared.Models.Beatmap beatmap_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.Beatmap Beatmap {
      get { return beatmap_; }
      set {
        beatmap_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType type_ = global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType.Passed;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 4;
    private int score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SongFinished);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SongFinished other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Player, other.Player)) return false;
      if (!object.Equals(Beatmap, other.Beatmap)) return false;
      if (Type != other.Type) return false;
      if (Score != other.Score) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (player_ != null) hash ^= Player.GetHashCode();
      if (beatmap_ != null) hash ^= Beatmap.GetHashCode();
      if (Type != global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType.Passed) hash ^= Type.GetHashCode();
      if (Score != 0) hash ^= Score.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (player_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Player);
      }
      if (beatmap_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Beatmap);
      }
      if (Type != global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType.Passed) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      if (Score != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Score);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (player_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Player);
      }
      if (beatmap_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Beatmap);
      }
      if (Type != global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType.Passed) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      if (Score != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Score);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (player_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Player);
      }
      if (beatmap_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Beatmap);
      }
      if (Type != global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType.Passed) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Score != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Score);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SongFinished other) {
      if (other == null) {
        return;
      }
      if (other.player_ != null) {
        if (player_ == null) {
          Player = new global::TournamentAssistantShared.Models.Player();
        }
        Player.MergeFrom(other.Player);
      }
      if (other.beatmap_ != null) {
        if (beatmap_ == null) {
          Beatmap = new global::TournamentAssistantShared.Models.Beatmap();
        }
        Beatmap.MergeFrom(other.Beatmap);
      }
      if (other.Type != global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType.Passed) {
        Type = other.Type;
      }
      if (other.Score != 0) {
        Score = other.Score;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (player_ == null) {
              Player = new global::TournamentAssistantShared.Models.Player();
            }
            input.ReadMessage(Player);
            break;
          }
          case 18: {
            if (beatmap_ == null) {
              Beatmap = new global::TournamentAssistantShared.Models.Beatmap();
            }
            input.ReadMessage(Beatmap);
            break;
          }
          case 24: {
            Type = (global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType) input.ReadEnum();
            break;
          }
          case 32: {
            Score = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (player_ == null) {
              Player = new global::TournamentAssistantShared.Models.Player();
            }
            input.ReadMessage(Player);
            break;
          }
          case 18: {
            if (beatmap_ == null) {
              Beatmap = new global::TournamentAssistantShared.Models.Beatmap();
            }
            input.ReadMessage(Beatmap);
            break;
          }
          case 24: {
            Type = (global::TournamentAssistantShared.Models.Packets.SongFinished.Types.CompletionType) input.ReadEnum();
            break;
          }
          case 32: {
            Score = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SongFinished message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum CompletionType {
        [pbr::OriginalName("Passed")] Passed = 0,
        [pbr::OriginalName("Failed")] Failed = 1,
        [pbr::OriginalName("Quit")] Quit = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
