// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TournamentAssistantShared.Models {

  /// <summary>Holder for reflection information generated from state.proto</summary>
  public static partial class StateReflection {

    #region Descriptor
    /// <summary>File descriptor for state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtzdGF0ZS5wcm90bxIgVG91cm5hbWVudEFzc2lzdGFudFNoYXJlZC5Nb2Rl",
            "bHMaFXNlcnZlcl9zZXR0aW5ncy5wcm90bxoKdXNlci5wcm90bxoRY29yZV9z",
            "ZXJ2ZXIucHJvdG8izAEKBVN0YXRlEkkKD3NlcnZlcl9zZXR0aW5ncxgBIAEo",
            "CzIwLlRvdXJuYW1lbnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxzLlNlcnZlclNl",
            "dHRpbmdzEjUKBXVzZXJzGAIgAygLMiYuVG91cm5hbWVudEFzc2lzdGFudFNo",
            "YXJlZC5Nb2RlbHMuVXNlchJBCgtrbm93bl9ob3N0cxgDIAMoCzIsLlRvdXJu",
            "YW1lbnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxzLkNvcmVTZXJ2ZXJCI6oCIFRv",
            "dXJuYW1lbnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TournamentAssistantShared.Models.ServerSettingsReflection.Descriptor, global::TournamentAssistantShared.Models.UserReflection.Descriptor, global::TournamentAssistantShared.Models.CoreServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TournamentAssistantShared.Models.State), global::TournamentAssistantShared.Models.State.Parser, new[]{ "ServerSettings", "Users", "KnownHosts" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class State : pb::IMessage<State>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<State> _parser = new pb::MessageParser<State>(() => new State());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<State> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TournamentAssistantShared.Models.StateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public State() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public State(State other) : this() {
      serverSettings_ = other.serverSettings_ != null ? other.serverSettings_.Clone() : null;
      users_ = other.users_.Clone();
      knownHosts_ = other.knownHosts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public State Clone() {
      return new State(this);
    }

    /// <summary>Field number for the "server_settings" field.</summary>
    public const int ServerSettingsFieldNumber = 1;
    private global::TournamentAssistantShared.Models.ServerSettings serverSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TournamentAssistantShared.Models.ServerSettings ServerSettings {
      get { return serverSettings_; }
      set {
        serverSettings_ = value;
      }
    }

    /// <summary>Field number for the "users" field.</summary>
    public const int UsersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::TournamentAssistantShared.Models.User> _repeated_users_codec
        = pb::FieldCodec.ForMessage(18, global::TournamentAssistantShared.Models.User.Parser);
    private readonly pbc::RepeatedField<global::TournamentAssistantShared.Models.User> users_ = new pbc::RepeatedField<global::TournamentAssistantShared.Models.User>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TournamentAssistantShared.Models.User> Users {
      get { return users_; }
    }

    /// <summary>Field number for the "known_hosts" field.</summary>
    public const int KnownHostsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::TournamentAssistantShared.Models.CoreServer> _repeated_knownHosts_codec
        = pb::FieldCodec.ForMessage(26, global::TournamentAssistantShared.Models.CoreServer.Parser);
    private readonly pbc::RepeatedField<global::TournamentAssistantShared.Models.CoreServer> knownHosts_ = new pbc::RepeatedField<global::TournamentAssistantShared.Models.CoreServer>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TournamentAssistantShared.Models.CoreServer> KnownHosts {
      get { return knownHosts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as State);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(State other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ServerSettings, other.ServerSettings)) return false;
      if(!users_.Equals(other.users_)) return false;
      if(!knownHosts_.Equals(other.knownHosts_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (serverSettings_ != null) hash ^= ServerSettings.GetHashCode();
      hash ^= users_.GetHashCode();
      hash ^= knownHosts_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (serverSettings_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ServerSettings);
      }
      users_.WriteTo(output, _repeated_users_codec);
      knownHosts_.WriteTo(output, _repeated_knownHosts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (serverSettings_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ServerSettings);
      }
      users_.WriteTo(ref output, _repeated_users_codec);
      knownHosts_.WriteTo(ref output, _repeated_knownHosts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (serverSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerSettings);
      }
      size += users_.CalculateSize(_repeated_users_codec);
      size += knownHosts_.CalculateSize(_repeated_knownHosts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(State other) {
      if (other == null) {
        return;
      }
      if (other.serverSettings_ != null) {
        if (serverSettings_ == null) {
          ServerSettings = new global::TournamentAssistantShared.Models.ServerSettings();
        }
        ServerSettings.MergeFrom(other.ServerSettings);
      }
      users_.Add(other.users_);
      knownHosts_.Add(other.knownHosts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (serverSettings_ == null) {
              ServerSettings = new global::TournamentAssistantShared.Models.ServerSettings();
            }
            input.ReadMessage(ServerSettings);
            break;
          }
          case 18: {
            users_.AddEntriesFrom(input, _repeated_users_codec);
            break;
          }
          case 26: {
            knownHosts_.AddEntriesFrom(input, _repeated_knownHosts_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (serverSettings_ == null) {
              ServerSettings = new global::TournamentAssistantShared.Models.ServerSettings();
            }
            input.ReadMessage(ServerSettings);
            break;
          }
          case 18: {
            users_.AddEntriesFrom(ref input, _repeated_users_codec);
            break;
          }
          case 26: {
            knownHosts_.AddEntriesFrom(ref input, _repeated_knownHosts_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
