// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf/Models/packet_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TournamentAssistantShared.Models {

  /// <summary>Holder for reflection information generated from protobuf/Models/packet_type.proto</summary>
  public static partial class PacketTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for protobuf/Models/packet_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFwcm90b2J1Zi9Nb2RlbHMvcGFja2V0X3R5cGUucHJvdG8SIFRvdXJuYW1l",
            "bnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxzKpICCgpQYWNrZXRUeXBlEhMKD0Fj",
            "a25vd2xlZGdlbWVudBAAEgsKB0NvbW1hbmQQARILCgdDb25uZWN0EAISEwoP",
            "Q29ubmVjdFJlc3BvbnNlEAMSCQoFRXZlbnQQBBIICgRGaWxlEAUSFAoQRm9y",
            "d2FyZGluZ1BhY2tldBAGEg4KCkxvYWRlZFNvbmcQBxIMCghMb2FkU29uZxAI",
            "EgwKCFBsYXlTb25nEAkSDAoIUmVzcG9uc2UQChIQCgxTY29yZVJlcXVlc3QQ",
            "CxIYChRTY29yZVJlcXVlc3RSZXNwb25zZRAMEhAKDFNvbmdGaW5pc2hlZBAN",
            "EgwKCFNvbmdMaXN0EA4SDwoLU3VibWl0U2NvcmUQD0IjqgIgVG91cm5hbWVu",
            "dEFzc2lzdGFudFNoYXJlZC5Nb2RlbHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::TournamentAssistantShared.Models.PacketType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PacketType {
    [pbr::OriginalName("Acknowledgement")] Acknowledgement = 0,
    [pbr::OriginalName("Command")] Command = 1,
    [pbr::OriginalName("Connect")] Connect = 2,
    [pbr::OriginalName("ConnectResponse")] ConnectResponse = 3,
    [pbr::OriginalName("Event")] Event = 4,
    [pbr::OriginalName("File")] File = 5,
    [pbr::OriginalName("ForwardingPacket")] ForwardingPacket = 6,
    [pbr::OriginalName("LoadedSong")] LoadedSong = 7,
    [pbr::OriginalName("LoadSong")] LoadSong = 8,
    [pbr::OriginalName("PlaySong")] PlaySong = 9,
    [pbr::OriginalName("Response")] Response = 10,
    [pbr::OriginalName("ScoreRequest")] ScoreRequest = 11,
    [pbr::OriginalName("ScoreRequestResponse")] ScoreRequestResponse = 12,
    [pbr::OriginalName("SongFinished")] SongFinished = 13,
    [pbr::OriginalName("SongList")] SongList = 14,
    [pbr::OriginalName("SubmitScore")] SubmitScore = 15,
  }

  #endregion

}

#endregion Designer generated code
