// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf/Models/state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TournamentAssistantShared.Models {

  /// <summary>Holder for reflection information generated from protobuf/Models/state.proto</summary>
  public static partial class StateReflection {

    #region Descriptor
    /// <summary>File descriptor for protobuf/Models/state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtwcm90b2J1Zi9Nb2RlbHMvc3RhdGUucHJvdG8SIFRvdXJuYW1lbnRBc3Np",
            "c3RhbnRTaGFyZWQuTW9kZWxzGiVwcm90b2J1Zi9Nb2RlbHMvc2VydmVyX3Nl",
            "dHRpbmdzLnByb3RvGhxwcm90b2J1Zi9Nb2RlbHMvcGxheWVyLnByb3RvGiFw",
            "cm90b2J1Zi9Nb2RlbHMvY29vcmRpbmF0b3IucHJvdG8aG3Byb3RvYnVmL01v",
            "ZGVscy9tYXRjaC5wcm90bxolcHJvdG9idWYvTW9kZWxzL3F1YWxpZmllcl9l",
            "dmVudC5wcm90bxohcHJvdG9idWYvTW9kZWxzL2NvcmVfc2VydmVyLnByb3Rv",
            "IpEDCgVTdGF0ZRJJCg9zZXJ2ZXJfc2V0dGluZ3MYASABKAsyMC5Ub3VybmFt",
            "ZW50QXNzaXN0YW50U2hhcmVkLk1vZGVscy5TZXJ2ZXJTZXR0aW5ncxI5Cgdw",
            "bGF5ZXJzGAIgASgLMiguVG91cm5hbWVudEFzc2lzdGFudFNoYXJlZC5Nb2Rl",
            "bHMuUGxheWVyEkMKDGNvb3JkaW5hdG9ycxgDIAEoCzItLlRvdXJuYW1lbnRB",
            "c3Npc3RhbnRTaGFyZWQuTW9kZWxzLkNvb3JkaW5hdG9yEjgKB21hdGNoZXMY",
            "BCABKAsyJy5Ub3VybmFtZW50QXNzaXN0YW50U2hhcmVkLk1vZGVscy5NYXRj",
            "aBJACgZldmVudHMYBSABKAsyMC5Ub3VybmFtZW50QXNzaXN0YW50U2hhcmVk",
            "Lk1vZGVscy5RdWFsaWZpZXJFdmVudBJBCgtrbm93bl9ob3N0cxgGIAEoCzIs",
            "LlRvdXJuYW1lbnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxzLkNvcmVTZXJ2ZXJC",
            "I6oCIFRvdXJuYW1lbnRBc3Npc3RhbnRTaGFyZWQuTW9kZWxzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::TournamentAssistantShared.Models.ServerSettingsReflection.Descriptor, global::TournamentAssistantShared.Models.PlayerReflection.Descriptor, global::TournamentAssistantShared.Models.CoordinatorReflection.Descriptor, global::TournamentAssistantShared.Models.MatchReflection.Descriptor, global::TournamentAssistantShared.Models.QualifierEventReflection.Descriptor, global::TournamentAssistantShared.Models.CoreServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TournamentAssistantShared.Models.State), global::TournamentAssistantShared.Models.State.Parser, new[]{ "ServerSettings", "Players", "Coordinators", "Matches", "Events", "KnownHosts" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class State : pb::IMessage<State>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<State> _parser = new pb::MessageParser<State>(() => new State());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<State> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TournamentAssistantShared.Models.StateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public State() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public State(State other) : this() {
      serverSettings_ = other.serverSettings_ != null ? other.serverSettings_.Clone() : null;
      players_ = other.players_ != null ? other.players_.Clone() : null;
      coordinators_ = other.coordinators_ != null ? other.coordinators_.Clone() : null;
      matches_ = other.matches_ != null ? other.matches_.Clone() : null;
      events_ = other.events_ != null ? other.events_.Clone() : null;
      knownHosts_ = other.knownHosts_ != null ? other.knownHosts_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public State Clone() {
      return new State(this);
    }

    /// <summary>Field number for the "server_settings" field.</summary>
    public const int ServerSettingsFieldNumber = 1;
    private global::TournamentAssistantShared.Models.ServerSettings serverSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TournamentAssistantShared.Models.ServerSettings ServerSettings {
      get { return serverSettings_; }
      set {
        serverSettings_ = value;
      }
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 2;
    private global::TournamentAssistantShared.Models.Player players_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TournamentAssistantShared.Models.Player Players {
      get { return players_; }
      set {
        players_ = value;
      }
    }

    /// <summary>Field number for the "coordinators" field.</summary>
    public const int CoordinatorsFieldNumber = 3;
    private global::TournamentAssistantShared.Models.Coordinator coordinators_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TournamentAssistantShared.Models.Coordinator Coordinators {
      get { return coordinators_; }
      set {
        coordinators_ = value;
      }
    }

    /// <summary>Field number for the "matches" field.</summary>
    public const int MatchesFieldNumber = 4;
    private global::TournamentAssistantShared.Models.Match matches_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TournamentAssistantShared.Models.Match Matches {
      get { return matches_; }
      set {
        matches_ = value;
      }
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int EventsFieldNumber = 5;
    private global::TournamentAssistantShared.Models.QualifierEvent events_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TournamentAssistantShared.Models.QualifierEvent Events {
      get { return events_; }
      set {
        events_ = value;
      }
    }

    /// <summary>Field number for the "known_hosts" field.</summary>
    public const int KnownHostsFieldNumber = 6;
    private global::TournamentAssistantShared.Models.CoreServer knownHosts_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::TournamentAssistantShared.Models.CoreServer KnownHosts {
      get { return knownHosts_; }
      set {
        knownHosts_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as State);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(State other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ServerSettings, other.ServerSettings)) return false;
      if (!object.Equals(Players, other.Players)) return false;
      if (!object.Equals(Coordinators, other.Coordinators)) return false;
      if (!object.Equals(Matches, other.Matches)) return false;
      if (!object.Equals(Events, other.Events)) return false;
      if (!object.Equals(KnownHosts, other.KnownHosts)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (serverSettings_ != null) hash ^= ServerSettings.GetHashCode();
      if (players_ != null) hash ^= Players.GetHashCode();
      if (coordinators_ != null) hash ^= Coordinators.GetHashCode();
      if (matches_ != null) hash ^= Matches.GetHashCode();
      if (events_ != null) hash ^= Events.GetHashCode();
      if (knownHosts_ != null) hash ^= KnownHosts.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (serverSettings_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ServerSettings);
      }
      if (players_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Players);
      }
      if (coordinators_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Coordinators);
      }
      if (matches_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Matches);
      }
      if (events_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Events);
      }
      if (knownHosts_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(KnownHosts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (serverSettings_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ServerSettings);
      }
      if (players_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Players);
      }
      if (coordinators_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Coordinators);
      }
      if (matches_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Matches);
      }
      if (events_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Events);
      }
      if (knownHosts_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(KnownHosts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (serverSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerSettings);
      }
      if (players_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Players);
      }
      if (coordinators_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Coordinators);
      }
      if (matches_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Matches);
      }
      if (events_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Events);
      }
      if (knownHosts_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(KnownHosts);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(State other) {
      if (other == null) {
        return;
      }
      if (other.serverSettings_ != null) {
        if (serverSettings_ == null) {
          ServerSettings = new global::TournamentAssistantShared.Models.ServerSettings();
        }
        ServerSettings.MergeFrom(other.ServerSettings);
      }
      if (other.players_ != null) {
        if (players_ == null) {
          Players = new global::TournamentAssistantShared.Models.Player();
        }
        Players.MergeFrom(other.Players);
      }
      if (other.coordinators_ != null) {
        if (coordinators_ == null) {
          Coordinators = new global::TournamentAssistantShared.Models.Coordinator();
        }
        Coordinators.MergeFrom(other.Coordinators);
      }
      if (other.matches_ != null) {
        if (matches_ == null) {
          Matches = new global::TournamentAssistantShared.Models.Match();
        }
        Matches.MergeFrom(other.Matches);
      }
      if (other.events_ != null) {
        if (events_ == null) {
          Events = new global::TournamentAssistantShared.Models.QualifierEvent();
        }
        Events.MergeFrom(other.Events);
      }
      if (other.knownHosts_ != null) {
        if (knownHosts_ == null) {
          KnownHosts = new global::TournamentAssistantShared.Models.CoreServer();
        }
        KnownHosts.MergeFrom(other.KnownHosts);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (serverSettings_ == null) {
              ServerSettings = new global::TournamentAssistantShared.Models.ServerSettings();
            }
            input.ReadMessage(ServerSettings);
            break;
          }
          case 18: {
            if (players_ == null) {
              Players = new global::TournamentAssistantShared.Models.Player();
            }
            input.ReadMessage(Players);
            break;
          }
          case 26: {
            if (coordinators_ == null) {
              Coordinators = new global::TournamentAssistantShared.Models.Coordinator();
            }
            input.ReadMessage(Coordinators);
            break;
          }
          case 34: {
            if (matches_ == null) {
              Matches = new global::TournamentAssistantShared.Models.Match();
            }
            input.ReadMessage(Matches);
            break;
          }
          case 42: {
            if (events_ == null) {
              Events = new global::TournamentAssistantShared.Models.QualifierEvent();
            }
            input.ReadMessage(Events);
            break;
          }
          case 50: {
            if (knownHosts_ == null) {
              KnownHosts = new global::TournamentAssistantShared.Models.CoreServer();
            }
            input.ReadMessage(KnownHosts);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (serverSettings_ == null) {
              ServerSettings = new global::TournamentAssistantShared.Models.ServerSettings();
            }
            input.ReadMessage(ServerSettings);
            break;
          }
          case 18: {
            if (players_ == null) {
              Players = new global::TournamentAssistantShared.Models.Player();
            }
            input.ReadMessage(Players);
            break;
          }
          case 26: {
            if (coordinators_ == null) {
              Coordinators = new global::TournamentAssistantShared.Models.Coordinator();
            }
            input.ReadMessage(Coordinators);
            break;
          }
          case 34: {
            if (matches_ == null) {
              Matches = new global::TournamentAssistantShared.Models.Match();
            }
            input.ReadMessage(Matches);
            break;
          }
          case 42: {
            if (events_ == null) {
              Events = new global::TournamentAssistantShared.Models.QualifierEvent();
            }
            input.ReadMessage(Events);
            break;
          }
          case 50: {
            if (knownHosts_ == null) {
              KnownHosts = new global::TournamentAssistantShared.Models.CoreServer();
            }
            input.ReadMessage(KnownHosts);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
